import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { TailwindIndicator } from "@/components/tailwind-indicator";
import { fontSans } from "@/lib/fonts";
import { ThemeToggle } from "@/components/theme-toggler";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={fontSans.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="relative flex min-h-screen flex-col">
            <div className="flex-1">{children}</div>
          </div>
          <div className="fixed bottom-1 right-1 z-10">
            <ThemeToggle />
          </div>
          <TailwindIndicator />
        </ThemeProvider>
      </body>
    </html>
  );
}
